repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: poetry run ruff format
        language: system
        types: [python]
      - id: ruff-check
        name: ruff-check
        entry: poetry run ruff check
        language: system
        types: [python]