name: CI

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [dev]  # можно убрать, если не нужно на пуши

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Poetry
        run: pip install poetry

      - name: Install deps (with dev)
        run: poetry install --no-interaction --no-ansi --with dev

      - name: Ruff format (check only)
        run: poetry run ruff format --check .

      - name: Ruff lint
        run: poetry run ruff check .

      - name: Pytest
        env:
          DJANGO_SETTINGS_MODULE: config.settings
          PYTHONPATH: ${{ github.workspace }}
        run: poetry run pytest -q
